os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3

install:
    - export SWIFT_VERSION="4.0"
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
    - swift build
    - swift build -c release
    - swift test
