os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9

install:
    - brew update # This is to fix https://github.com/travis-ci/travis-ci/issues/8552
    - brew tap vapor/homebrew-tap
    - brew update
    - brew install vapor

script:
    - swift build
    - swift build -c release
    - swift test
